// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shop.Infrastructure;

namespace Shop.Infrastructure.Migrations.DemoShop
{
    [DbContext(typeof(DemoShopContext))]
    partial class DemoShopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Shop.Core.Entities.Productos", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("codigo")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnName("marca")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnName("nombre")
                        .HasMaxLength(60)
                        .IsUnicode(false);

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnName("precioUnitario")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<int>("Stock")
                        .HasColumnName("stock");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnName("tipo")
                        .HasMaxLength(25)
                        .IsUnicode(false);

                    b.Property<string>("Unidades")
                        .IsRequired()
                        .HasColumnName("unidades")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.HasKey("Codigo")
                        .HasName("PK__Producto__40F9A2077F076D42");

                    b.ToTable("Productos");
                });
#pragma warning restore 612, 618
        }
    }
}
